#!/bin/sh

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_ASSERTIONS=true \
  -DCLANG_BUILD_EXAMPLES=true \
  -DMAPA_AGGRESSIVE_LOOP_ANALYSIS=true \
  -DMAPA_USE_SYMBOLIC_EXPRESSION_CONSTANT_CACHE=false \
  -DMAPA_AGGRESSIVE_SYMBOLIC_EXPRESSION_COMPARE=true \
  ..
make -j32
